name: Dozer General

on:
  issues:
    types: [opened, edited, milestoned]
  discussion:
    types: [created, edited, deleted]
  discussion_comment:
    types: [created, deleted, edited]
concurrency:
  group: general

jobs:
  notify:
    name: Discord General
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1077462259657363466/pUMatcj219VEFb1z3s4JVF544mMKpmYRWeRxneXyqEc6qXTPa747RnkX3-VhZVsFyLPv
        uses: Ilshidur/action-discord@master
