name: Dozer General

on:
  push:
    branches: [main]
concurrency:
  group: main

jobs:
  notify:
    name: Discord Main
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1077462259657363466/pUMatcj219VEFb1z3s4JVF544mMKpmYRWeRxneXyqEc6qXTPa747RnkX3-VhZVsFyLPv
          DISCORD_EMBEDS: '[ { 
           "title": " ${{ github.actor }} pushed to `main` :rocket:",
           "author": {  "icon_url": "https://avatars.githubusercontent.com/${{ github.actor }}", "name": "${{ github.actor }}", "url": "https://github.com/${{ github.actor }}" },
          "fields": [
            { "name": "Commit", "value": "[${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})"},
            { "name": "Repository", "value": "[getdozer/dozer](https://github.com/getdozer/dozer)" },
            { "name": "Message", "value": "${{ github.event.head_commit.message }}"}
          ],
          "color": 990099
          }]'
        uses: Ilshidur/action-discord@master 